---
:tagger_configuration:
  :juman_normal:
    :tagger: :juman
    :option: -e2
    :grammar: :juman
    :pattern: "^([^@ ][^ ]*) [^ ]+ [^ ]+ ([^ ]+) [^ ]+ ([^ ]+).+?\n"
    :encoding: euc-jp
    :description: JUMAN with default dictionary
  :juman_autodic:
    :tagger: :juman
    :option: -e2 -r $HOME/.jumanautorc
    :grammar: :juman
    :pattern: "^([^@ ][^ ]*) [^ ]+ [^ ]+ ([^ ]+) [^ ]+ ([^ ]+).+?\n"
    :encoding: euc-jp
    :description: JUMAN with default dictionary and autodic
  :mecab_unidic:
    :tagger: :mecab
    :option: -d $HOME/usr/lib/mecab/dic/unidic
    :grammar: :unidic
    :pattern: "^([^\t]+)\t([^,]+),([^,]+).+?\n"
    :encoding: utf-8
    :description: MeCab with UniDic
  :mecab_ipadic:
    :tagger: :mecab
    :option: -d $HOME/usr/lib/mecab/dic/ipadic
    :grammar: :ipadic
    :pattern: "^([^\t]+)\t([^,]+),([^,]+).+?\n"
    :encoding: utf-8
    :description: MeCab with IPA Dictionary
:grammar_pairs:
- :combination:
  - :juman
  - :unidic
  :config: grammar/juman_unidic.yml
- :combination:
  - :juman
  - :ipadic
  :config: grammar/juman_ipadic.yml
- :combination:
  - :unidic
  - :ipadic
  :config: grammar/unidic_ipadic.yml
