---
:tagger_config:
  :juman_normal:
    :command: juman
    :grammar: :juman
    :pattern: "^([^@ ][^ ]*) [^ ]+ [^ ]+ ([^ ]+) [^ ]+ ([^ ]+).+?\n"
    :encoding: euc-jp
    :description: JUMAN with default dictionary
  :juman_autodic:
    :command: juman -r $HOME/.jumanautorc
    :grammar: :juman
    :pattern: "^([^@ ][^ ]*) [^ ]+ [^ ]+ ([^ ]+) [^ ]+ ([^ ]+).+?\n"
    :encoding: euc-jp
    :description: JUMAN with default dictionary and autodic
  :mecab_unidic:
    :command: mecab -d $HOME/usr/lib/mecab/dic/unidic
    :grammar: :unidic
    :pattern: "^([^\t]+)\t([^,]+),([^,]+).+?\n"
    :encoding: utf-8
    :description: MeCab with UniDic
  :mecab_ipadic:
    :command: mecab -d $HOME/usr/lib/mecab/dic/ipadic
    :grammar: :ipadic
    :pattern: "^([^\t]+)\t([^,]+),([^,]+).+?\n"
    :encoding: utf-8
    :description: MeCab with IPA Dictionary
:grammar_configs: :hoge
